# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gr8vGQG9Ef2q3CsVsRDwBlZBJb-UG4Ci

# this line of code will take an input using  the input function
"""

print("hello " + input("what is your name?") + "!")

glass1 = "milk"
glass2 = "juice"
a=glass2
glass2=glass1
glass1=a
print(glass1)
print(glass2)

glass1 = "milk"
glass2 = "juice"
a=glass2
glass1=a
b=glass1
glass2=b
glass2=glass1
print(glass1)
print(glass2)

name = "jack"
print(name)

name="angle"
print(name)

a = "hello world"
print(len(a))

print(len(input("what is your name")))

username = input("what is your name?")
length = len(username)
print(length)

"""band name genrater

"""

print("welcome to the band name genrater")
city = input("which city did you grow up in?\n")
pet = input("what is the name of your pet?\n")
print("your band name could be " + city + " " +pet)