# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtHqPrGb8pdxJw0I-gJwhBiboEHHXhSQ

subscrpting
"""

print("hello"[0])

"""string"""

print("123" + "345")

"""interger"""

print(123 + 345)

"""large integer"""

print(123_456_789)

"""float"""

print(3.1444)

"""boolean"""

print(True)
print(False)

len("hello")

print(type("hello"))

print(int("123") +int("456"))
int("123")

di = 84 / 1.65 ** 2
print(di)
print(int(di))

print(round(di))
print(round(di, 2))
print(round(234242.423434))

s = 0.0
s += 0.345
print(s)

s = 0
h = 1.6
i_s = True
print(f"socre of sai = {s}, and ravi socre ={h} and is both {i_s}")

height = 1.65
weight = 84

# Write your code here.
# Calculate the bmi using weight and height.
bmi = (weight/height) ** 2

print(bmi)

"""Tip calculater"""

print(150 * 1.12/5)

print("welcome to the tip calaculater")
bill = float(input("what was the total bills ? $"))
tip = int(input("how much tip would you like to give ? 10, 12, or 15 ? "))
people = int(input("how many people to split the bill ? "))
tip_as_percent = tip / 100
total_tip_amount = bill * tip_as_percent
total_bill = bill + total_tip_amount
bill_per_person = total_bill / people
final_amount = round(bill_per_person, 2)
print(f"each person should pay: ${final_amount}")

print(13.32 * 10)