# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1urcce8im15tFDMKvC9vjGhol9y_jnf7K
"""

print("welcome to the rollercoster")
height=int(input("enter your height in cm: "))

if height >= 120:
  print("you can ride the rollercoster.")
else:
  print("you can't ride the rollercoster.")

a = int(input("what is the number you want to check"))
if a % 2 == 0:
  print('even')
else :
  print('odd')

height = int(input("enter your height in cm"))
if height >=120:
  print("you can ride the rollercoster")
  age = int(input("enter your age"))
  if age >= 18:
    print("ticket price is 12 rupess")
  else:
    print("ticket price is 7 rupess")
else:
  print("you can't ride the rollercoster")

height = int(input("enter your height in cm"))
if height >=120:
  print("you can ride the rollercoster")
  age = int(input("enter your age"))
  if age <= 12:
    bill = 5
    print("ticket price is 5 rupess")
  elif age <= 18:
    bill = 7
    print("ticket price is 7 rupess")
  elif age >=45 and age<=55:
    bill = 0
    print("your going to haven are hell ok you got free rid raa koja")
  else:
    bill = 16
    print("ticket price is 16 rupess")
  a=input("if you want to take photo yes or no")
  if a == 'y':
    bill = bill + 3
    print(f"total bill is {bill}")
  else:
    print("ok carry on")

else:
  print("you can't ride the rollercoster")

weight = 85
height = 1.85

bmi = weight / (height ** 2)

# 🚨 Do not modify the values above
# Write your code below 👇
if bmi<=18.5 :
    print("underweight")
elif bmi<=25 :
    print("normal weight")
elif bmi<=29.9 :
    print("overweight")

print("welcome kaki raata pizza shop")
size = input("which size of pizza you want s or m or l")
peppor = input("you want peppor y or n")
chesse = input("you want chesse")
if size == 's' or 'm' or 'l' :
  if size == 's' :
    bill =10
  elif size == 'm' :
    bill = 15
  else:
    bill = 20
  if peppor == 'y' :
    if size == 's' :
      bill = bill + 2
    else:
      bill = bill + 3
  if chesse == 'y' :
    bill = bill + 1
  print(f"total bill {bill}")

"""                            _.--.
                        _.-'_:-'||
                    _.-'_.-::::'||
               _.-:'_.-::::::'  ||
             .'`-.-:::::::'     ||
            /.'`;|:::::::'      ||_
           ||   ||::::::'     _.;._'-._
           ||   ||:::::'  _.-!oo @.!-._'-.
           \'.  ||:::::.-!()oo @!()@.-'_.|
            '.'-;|:.-'.&$@.& ()$%-'o.'\U||
              `>'-.!@%()@'@_%-'_.-o _.|'||
               ||-._'-.@.-'_.-' _.-o  |'||
               ||=[ '-._.-\U/.-'    o |'||
               || '-.]=|| |'|      o  |'||
               ||      || |'|        _| ';
               ||      || |'|    _.-'_.-'
               |'-._   || |'|_.-'_.-'
            jgs '-._'-.|| |' `_.-'
                    '-.||_/.-'

"""

print("welcome to treasure island")
print("your mission is to find the trtouser")
a = input(" your at crossed where do you want to go ? type \"left\" or \"right\" ")
if a == "left" :
  b = input(' your wait or swim ')
  if b == "wait" :
    c = input(' which door you select? red or blue or yellow ')
    if c == "yellow" :
      print("you win")
    elif c == "red" :
      print(" burned by fire game over")
    else :
      print("eaten by beass game over")
  else :
    print("attcked by trout game over ")
else:
  print("faill into a hole game over ")