# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j7-_EAjw7-cos1i_dPsSBSUPvV_N6Fl
"""

import random
randommodule = random.random()*100
print(randommodule)

randommodulefloat = random.uniform(1,100)
print(randommodulefloat)

ran = random.randint(0,1)
print(ran)

# Rock
rock ='''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

# Paper
paper ='''
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
'''

# Scissors
scisser ='''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
game_images = [rock, paper, scisser]
use_choise = int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n"))
if use_choise >=0 and use_choise <=2:
  print(game_images[use_choise])
computer_choise = random.randint(0,2)
print("computer chose")
print(game_images[computer_choise])
print(f"Computer chose: {computer_choise}")
if use_choise == 0 and computer_choise == 2:
    print("you win")
elif use_choise > computer_choise:
    print("you lose")
elif use_choise < computer_choise:
    print("you win")
elif use_choise == computer_choise:
    print("draw")
else:
    print("you typed an invalide number")