# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-LTcvLWTDuAMFkA5XUOE7Ya9VA3J0li
"""

import random as randon
nr_letters = ['a','b','c','d','e','f','g','h','i','j','k','l','o','p','q','s','u','v','w','x','y','z']
nr_numbers = ['1','2','3','4','5','6','7','8','9','0']
import random as randon
nr_letters = ['a','b','c','d','e','f','g','h','i','j','k','l','o','p','q','s','u','v','w','x','y','z']
nr_numbers = ['1','2','3','4','5','6','7','8','9','0']
nr_symbol = ['!','@','#','$','%','^','&','*','+']
password_list = []
for char in range(0 , 1): # Replace ange(1, nr_letters) with 1 for a single iteration
    password_list.append(randon.choice(nr_letters))
for char in range(0 , len(nr_numbers)): # Use len() to iterate over the list
    password_list.append(randon.choice(nr_numbers))
for char in range(0 , len(nr_symbol)): # Use len() to iterate over the list
    password_list.append(randon.choice(nr_symbol))
print(password_list)
randon.shuffle(password_list) # Remove the extra randon.
print(password_list)
password = ""
for char in password_list:
    password += char
print(f"your password is {password}")
    password_list.append(randon.choice(nr_numbers))
for char in range(0 , nr_symbol):
    password_list.append(randon.choice(nr_symbol))
print(password_list)
randon.randon.shuffle(password_list)
print(password_list)
password = ""
for char in password_list:
    password += char
print(f"your password is {password}")